### ISSUE TITLE
Entity colour name not visible in loglist

### ISSUE THREAD

**Issue by alexandrosmagos** [bbbenji/synthwave-hass#20]
Same problem on both desktop and the android app. In loglist, the entity color is the same with the backround and not visible. After I go back to the overview and the back, the color is white.

![android 1](https://user-images.githubusercontent.com/12672076/75438469-ad73c780-5960-11ea-810c-644bffcc12ff.jpg)
![android 2](https://user-images.githubusercontent.com/12672076/75438474-af3d8b00-5960-11ea-8219-40f3c8253d31.jpg)
![desktop 1](https://user-images.githubusercontent.com/12672076/75438479-b1074e80-5960-11ea-9591-6d5caa594394.png)
![desktop 2](https://user-images.githubusercontent.com/12672076/75438481-b19fe500-5960-11ea-9219-51d2441ee3d7.png)

**Comment by bbbenji** [comment]
Styling entities on the Logbook and Developer Tools pages is basically a workaround handled by https://github.com/bbbenji/synthwave-hass-extras. Because the JS is loaded on the Overview page, you must first visit that before loading the Logbook or Developer Tools page.

Until Home Assistant changes some color definitions, this is the only practical solution for the moment as far as I can tell...

**Comment by CyanoFresh** [comment]
@bbbenji maybe some pull request is needed for HA?

**Comment by bbbenji** [comment]
Absolutely. Closing for now as Synthwave has a workaround implemented and I am waiting on changes to HA itself to resolve this.
